version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name finalwork5 --s3-location s3://finalwork5/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src